name: Push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install
        env:
          # Skip integrity check; browserslist@4.17.0 has the wrong checksum.
          CI: false
          YARN_CHECKSUM_BEHAVIOR: update

  build-demo:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install
        env:
          # Skip integrity check; browserslist@4.17.0 has the wrong checksum.
          CI: false
          YARN_CHECKSUM_BEHAVIOR: update
      - name: 'Build @glossary/react'
        run: yarn build
        working-directory: ./packages/react
        env:
          # Skip integrity check; browserslist@4.17.0 has the wrong checksum.
          CI: false
          YARN_CHECKSUM_BEHAVIOR: update
      - name: Build
        run: yarn && yarn build
        working-directory: ./packages/demo
        env:
          # Skip integrity check; browserslist@4.17.0 has the wrong checksum.
          CI: false
          YARN_CHECKSUM_BEHAVIOR: update
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: build
          path: build

  publish-build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Publish
        working-directory: ./packages/build
        run: >
          yarn config set npmAuthToken $NPM_AUTH_TOKEN;
          yarn npm publish --tolerate-republish;
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  publish-react:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install
        env:
          # Skip integrity check; browserslist@4.17.0 has the wrong checksum.
          CI: false
          YARN_CHECKSUM_BEHAVIOR: update
      - name: Build
        run: yarn build
        working-directory: ./packages/react
      - name: Publish
        working-directory: ./packages/react
        run: >
          yarn config set npmAuthToken $NPM_AUTH_TOKEN;
          yarn npm publish --tolerate-republish;
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  github-pages:
    needs: build-demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          clean: true
          folder: build
          single-commit: true

on:
  push:
    branches: [main]
